# This file was generated by GoReleaser. DO NOT EDIT.
class Myproject < Formula
  desc ""
  homepage "https://github.com/divanvisagie/new"
  url "https://github.com/divanvisagie/new/releases/download/v0.0.10/new_0.0.10_darwin_amd64.tar.gz"
  version "0.0.10"
  sha256 "4819a4452822e89cec7f8dd335e5552d9541b3d138bbac5f2680f6824612f3a8"

  def install
    bin.install "new"
  end
end
