# This file was generated by GoReleaser. DO NOT EDIT.
class New < Formula
  desc "generate projects from git repositories"
  homepage "https://github.com/divanvisagie/new"
  url "https://github.com/divanvisagie/new/releases/download/v0.5.1/new_0.5.1_darwin_amd64.tar.gz"
  version "0.5.1"
  sha256 "a661688af5f5cbda722b9df0252017847f003586260aaf448d4dbcf42832692e"

  def install
    bin.install "new"
  end
end
