# This file was generated by GoReleaser. DO NOT EDIT.
class New < Formula
  desc "generate projects from git repositories"
  homepage "https://github.com/divanvisagie/new"
  url "https://github.com/divanvisagie/new/releases/download/v0.1.0/new_0.1.0_darwin_amd64.tar.gz"
  version "0.1.0"
  sha256 "afe2281b5febaecf777692aa78f9d8a051a817b0b300900de3e7147fdf77c6b9"

  def install
    bin.install "new"
  end
end
